// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessions = `-- name: CreateSessions :one
INSERT INTO sessions (
    id,
    username,
    refresh_token,
    client_ip,
    user_agent,
    is_blocked,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, username, refresh_token, client_ip, user_agent, is_blocked, expires_at, created_at
`

type CreateSessionsParams struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	RefreshToken string             `json:"refresh_token"`
	ClientIp     string             `json:"client_ip"`
	UserAgent    string             `json:"user_agent"`
	IsBlocked    bool               `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSessions(ctx context.Context, arg CreateSessionsParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSessions,
		arg.ID,
		arg.Username,
		arg.RefreshToken,
		arg.ClientIp,
		arg.UserAgent,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RefreshToken,
		&i.ClientIp,
		&i.UserAgent,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessions = `-- name: GetSessions :one
SELECT id, username, refresh_token, client_ip, user_agent, is_blocked, expires_at, created_at FROM sessions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSessions(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessions, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RefreshToken,
		&i.ClientIp,
		&i.UserAgent,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
